sudo: required

services:
  - docker

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com  

script:
  - echo $DB_HOST
  - docker build -t azizmavlyanov/laravel-back:v1 --build-arg DB_HOST=$DB_HOST --build-arg DB_DATABASE=$DB_DATABASE --build-arg DB_USERNAME=$DB_USERNAME --build-arg DB_PASSWORD=$DB_PASSWORD --build-arg JWT_SECRET=$JWT_SECRET --build-arg MAIL_PASSWORD=$MAIL_PASSWORD -f Dockerfile .
  - docker tag azizmavlyanov/laravel-back:v1 registry.heroku.com/$HEROKU_APP/web 

deploy:   
  provider: script
  script: 
          docker push azizmavlyanov/laravel-back:v1;
          docker push registry.heroku.com/$HEROKU_APP/web;
          heroku container:release web --app $HEROKU_APP
  on:
    branch: master
